# Adding HTTPD configuration programatically /lotto 
Alias /lotto /home/pi/RPIService/lotto/ 
<Directory "/home/pi/RPIService/lotto/"> 

        Options All
        AllowOverride All
        Require all granted
        Order allow,deny
        Allow from all
</Directory>
    