# This is Programmed Configuration

[Movies]
path = /home/pi/mounts/Movies
writable=Yes
create mask=0777
directory mask=0777
public=no

[Temp]
path = /home/pi/mounts/Temp
writable=Yes
create mask=0777
director mask=077
public=no
